spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: skillbox
    password: skillbox
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
  liquibase:
    change-log: classpath:db/change-log/db.changelog-master.xml
    enabled: false